### PR TITLE
Port to use awilix-router-core

### LINKED ISSUE #5: Integrate with awilix-router-core
Hey @talyssonoc — I've been working on a routing abstraction to make routing + dependency resolution super streamlined. The core package is [`awilix-router-core`](https://github.com/jeffijoe/awilix-router-core) which does not cater to any specific HTTP framework.

Here's an [example usage](https://github.com/jeffijoe/awilix-koa/tree/next#awesome-usage) and [reference implementation](https://github.com/jeffijoe/awilix-koa/blob/next/src/controller.ts) I did for the `awilix-koa` package.

**All the builder + decorator stuff resides in `awilix-router-core`, all you need to do is register the result with `app.get|post|...` as seen in the reference implementation.**

Would you be willing to work on this? If you need any help or if something could be more clear, please let me know.

Thanks again for maintaining `awilix-express`! 😄

### PR DESCRIPTION
**Pull request by talyssonoc**
Closes #5

### CODE REVIEW

**Comment by talyssonoc** [comment]
@ jeffijoe do you mind taking a look at that? :)

**Comment by talyssonoc** [comment]
@jeffijoe do you mind taking a look at that? :)

**Comment by jeffijoe** [comment]
For sure! I’ll review tomorrow. 😄

**Comment by talyssonoc** [comment]
Great, thanks a lot!

**Pull request merged**
