### PR TITLE
Handle errors in async routes

### PR DESCRIPTION
**Pull request by elunic**
We've been using `bottlejs` extensively but are looking to switch to Awilix to leverage its advanced capabilities when it comes to scoped and transient service instances as well as `awilix-express` for the decorator syntax.

We've written our own adapter for `express` and `bottlejs` (`bottlejs-express`). One thing we included that is immensely useful is handling of errors in routes that are `async functions`. When an async method (route) throws an error, that rejected promise is not handled by `express` or `awilix-express`.

As a result, each method would have to include a `try/catch` block, which is easy to forget, resulting in swallowed errors, or greatly reduces readability of the code.

The included PR introduces a wrapper for handling rejected promises coming from async routes. I have included as many tests as I thought were relevant. We're really looking forward to using this module, but it's not an option without this error handling.

Please let me know if there are any adjustments you think should still be made. Thanks!

### CODE REVIEW

**Comment by elunic** [comment]
No problem. Nobody wants their PR to break a repo!

**Comment by maxstrauch** [comment]
I really like this feature and would appreciate if it is merged very soon. 👍 

@talyssonoc could you merge it soon? (or: @jhoscar1 or @blove)

**Comment by jeffijoe** [comment]
I've reached out to @talyssonoc on Twitter to see if he would consider giving me contributing and publishing rights.

**Comment by jeffijoe** [comment]
@elunic @whefter @maxstrauch This has been released as v2.0.0 on npm — the major increment is due to the Awilix v3 -> v4 update.

Thanks for the PR!

**Comment by maxstrauch** [comment]
Thanks for merging in 👍 😄

**Pull request merged**
